Repository Y-Five/gbjs-be, pull requests merged in 2025-09, with the labels that each got.

#73 🔧Settings: 빌드 환경변수 파일 추가
  docker/Dockerfile
Labels: 🐞 bug

#75 🚀Deploy: CD 파일 수정
  .github/workflows/cd.yml
  docker/docker-compose-blue.yml
  docker/docker-compose-green.yml
Labels: 🐞 bug

#104 ♻️Refactor: 관광지 단일 조회 API 수정
  src/main/java/com/yfive/gbjs/domain/festival/service/FestivalServiceImpl.java
  src/main/java/com/yfive/gbjs/domain/spot/service/SpotServiceImpl.java
  src/main/java/com/yfive/gbjs/domain/user/dto/response/UserDetailResponse.java
  src/main/java/com/yfive/gbjs/domain/user/mapper/UserMapper.java
  src/main/java/com/yfive/gbjs/domain/user/service/UserServiceImpl.java
  src/main/java/com/yfive/gbjs/domain/weather/dto/response/WeatherResponse.java
  src/main/java/com/yfive/gbjs/domain/weather/service/WeatherService.java
  src/main/java/com/yfive/gbjs/domain/weather/service/WeatherServiceImpl.java
  src/main/java/com/yfive/gbjs/global/config/SecurityConfig.java
  src/main/java/com/yfive/gbjs/global/config/jwt/JwtProvider.java
Labels: ♻️ refactor, 🔴 priority: high

#114 ♻️Refactor: 경북씰 설명 추가
  src/main/java/com/yfive/gbjs/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/yfive/gbjs/global/qdrant/scheduler/DataIndexingScheduler.java
  src/main/java/com/yfive/gbjs/global/qdrant/scheduler/QdrantIndexerRunner.java
  src/main/java/com/yfive/gbjs/global/qdrant/service/DataIndexingService.java
  src/test/java/com/yfive/gbjs/global/qdrant/scheduler/TestQdrantIndexerRunner.java
Labels: ♻️ refactor
