Repository Y-Five/gbjs-be, pull requests merged in 2025-08, with the labels that each got.

#36 ♻️Refactor: 관광지 API 리팩토링
  build.gradle
  src/main/java/com/yfive/gbjs/domain/guide/controller/GuideController.java
  src/main/java/com/yfive/gbjs/domain/spot/controller/SpotController.java
  src/main/java/com/yfive/gbjs/domain/spot/controller/SpotControllerImpl.java
  src/main/java/com/yfive/gbjs/domain/spot/dto/response/SpotResponse.java
  src/main/java/com/yfive/gbjs/domain/spot/entity/SortBy.java
  src/main/java/com/yfive/gbjs/domain/spot/service/SpotService.java
  src/main/java/com/yfive/gbjs/domain/spot/service/SpotServiceImpl.java
Labels: ♻️ refactor, 🟠 priority: medium

#39 ♻️Refactor: 가이드 데이터 저장
  src/main/java/com/yfive/gbjs/domain/guide/config/AudioDataInitializer.java
  src/main/java/com/yfive/gbjs/domain/guide/controller/AudioGuideController.java
  src/main/java/com/yfive/gbjs/domain/guide/controller/GuideController.java
  src/main/java/com/yfive/gbjs/domain/guide/controller/GuideControllerImpl.java
  src/main/java/com/yfive/gbjs/domain/guide/converter/AudioGuideConverter.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/OpenApiBaseResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/StoryBasedListResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/ThemeBasedListResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/response/AudioDetailResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/response/AudioStoryListResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/response/GuideListResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/entity/AudioGuide.java
  src/main/java/com/yfive/gbjs/domain/guide/exception/GuideErrorStatus.java
  src/main/java/com/yfive/gbjs/domain/guide/repository/AudioGuideRepository.java
  src/main/java/com/yfive/gbjs/domain/guide/scheduler/AudioDataScheduler.java
  src/main/java/com/yfive/gbjs/domain/guide/service/GuideService.java
  src/main/java/com/yfive/gbjs/domain/guide/service/GuideServiceImpl.java
  src/main/java/com/yfive/gbjs/global/config/SecurityConfig.java
  src/main/java/com/yfive/gbjs/global/error/GlobalExceptionHandler.java
  src/test/java/com/yfive/gbjs/domain/guide/AudioGuideSync.java
  src/test/java/com/yfive/gbjs/domain/guide/controller/TestAudioGuideController.java
Labels: ♻️ refactor

#40 ️ ♻️refactor: 가이드 범위 정리
  src/main/java/com/yfive/gbjs/domain/guide/entity/AudioGuide.java
  src/main/java/com/yfive/gbjs/domain/guide/service/GuideServiceImpl.java
Labels: ♻️ refactor

#46 ♻️Refactor : Seal api 수정
  src/main/java/com/yfive/gbjs/domain/seal/controller/SealController.java
  src/main/java/com/yfive/gbjs/domain/seal/controller/SealControllerImpl.java
  src/main/java/com/yfive/gbjs/domain/seal/converter/SealConverter.java
  src/main/java/com/yfive/gbjs/domain/seal/converter/SealProductConverter.java
  src/main/java/com/yfive/gbjs/domain/seal/converter/UserSealConverter.java
  src/main/java/com/yfive/gbjs/domain/seal/dto/response/SealProductResponse.java
  src/main/java/com/yfive/gbjs/domain/seal/dto/response/SealResponse.java
  src/main/java/com/yfive/gbjs/domain/seal/dto/response/UserSealResponse.java
  src/main/java/com/yfive/gbjs/domain/seal/entity/Rarity.java
  src/main/java/com/yfive/gbjs/domain/seal/entity/Seal.java
  src/main/java/com/yfive/gbjs/domain/seal/entity/SortBy.java
  src/main/java/com/yfive/gbjs/domain/seal/entity/mapper/UserSeal.java
  src/main/java/com/yfive/gbjs/domain/seal/repository/UserSealRepository.java
  src/main/java/com/yfive/gbjs/domain/seal/service/SealService.java
  src/main/java/com/yfive/gbjs/domain/seal/service/SealServiceImpl.java
  src/main/java/com/yfive/gbjs/domain/user/service/UserService.java
  src/main/java/com/yfive/gbjs/domain/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#48 ️ ♻️refactor: seal location unique삭제
  src/main/java/com/yfive/gbjs/domain/seal/entity/Seal.java
Labels: ♻️ refactor

#49 ♻️Refactor: 기본 좌표값 수정
  src/main/java/com/yfive/gbjs/domain/weather/controller/WeatherController.java
  src/main/java/com/yfive/gbjs/domain/weather/service/WeatherServiceImpl.java
Labels: ♻️ refactor, 🔴 priority: high

#54 ♻️Refactor: 전통문화 관련 API 리팩토링
  src/main/java/com/yfive/gbjs/domain/tradition/controller/TraditionController.java
  src/main/java/com/yfive/gbjs/domain/tradition/controller/TraditionControllerImpl.java
  src/main/java/com/yfive/gbjs/domain/tradition/dto/request/TraditionRequest.java
  src/main/java/com/yfive/gbjs/domain/tradition/dto/response/TraditionResponse.java
  src/main/java/com/yfive/gbjs/domain/tradition/entity/Tradition.java
  src/main/java/com/yfive/gbjs/domain/tradition/mapper/TraditionMapper.java
  src/main/java/com/yfive/gbjs/domain/tradition/service/TraditionService.java
  src/main/java/com/yfive/gbjs/domain/tradition/service/TraditionServiceImpl.java
Labels: ♻️ refactor, 🔴 priority: high

#55 ♻️Refactor: 코드 리뷰 기반 수정사항 반영
  src/main/java/com/yfive/gbjs/domain/tradition/dto/request/TraditionRequest.java
Labels: ♻️ refactor

#65 ️ ♻️refactor: seal GeoJSON 적용
  src/main/java/com/yfive/gbjs/domain/guide/controller/AudioGuideController.java
  src/main/java/com/yfive/gbjs/domain/guide/dto/response/CoordinateValidationResponse.java
  src/main/java/com/yfive/gbjs/domain/guide/service/GuideService.java
  src/main/java/com/yfive/gbjs/domain/guide/service/GuideServiceImpl.java
  src/main/java/com/yfive/gbjs/domain/guide/util/GeoJsonBoundaryChecker.java
  src/test/java/com/yfive/gbjs/domain/guide/service/GuideServiceTest.java
Labels: ♻️ refactor, 🔴 priority: high
